### ISSUE TITLE
Exception in plugin 2.1.1: update failed for AnAction

### ISSUE THREAD

**Issue by allanlaal** [cherryleafroad/IntelliJ-Rust-Playground#11]
update failed for AnAction(com.cherryleafroad.rust.playground.actions.OpenCargoPlayReleaseBinaryAction, id=Rust.Playground.OpenReleaseBinary) with text=Release Binary
  
  kotlin.UninitializedPropertyAccessException: lateinit property cargoPlayPath has not been initialized
	  at com.cherryleafroad.rust.playground.services.CargoPlayProjectService.getCargoPlayPath(CargoPlayProjectService.kt:12)
	  at com.cherryleafroad.rust.playground.actions.OpenCargoPlayReleaseBinaryAction.update(OpenCargoFolderActions.kt:62)
	  at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
	  at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
	  at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:584)
	  at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:132)
	  at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$9(ActionUpdater.java:187)
	  at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	  at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	  at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	  at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$10(ActionUpdater.java:185)
	  at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	  at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	  at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	  at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	  at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	  at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	  at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	  at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	  at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	  at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	  at java.base/java.security.AccessController.doPrivileged(Native Method)
	  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	  at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	  at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	  at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	  at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	  at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by MolotovCherry** [comment]
This error is benign as far as operation of the plugin goes (can safely ignore).

However, do you have any reproduce steps for it? This one is hard to know how to reliably reproduce

**Comment by allanlaal** [comment]
happened while I was using IDEA for non-Rust stuff. IDEA suggested disabling the plugin, so your call on the severity ;)

**Comment by MolotovCherry** [comment]
Yeah, don't worry about "severity". This one won't cause any issues in the plugin other than the "annoying" error. You can use the plugin as normal without issue. I'll see if I can reproduce it later :)

**Comment by MolotovCherry** [comment]
Debugging this one is near impossible because it shouldn't even happen from what I knew, and it's quite a rare bug. 

Nevertheless, that doesn't matter. I made it impossible for it to happen again.

**Comment by MolotovCherry** [comment]
By the way, if you're so inclined, here's a build of the fixed version for you before it hits the market (version not yet updated, but code is still fixed).
[Rust Playground-2.1.1.zip](https://github.com/cherryleafroad/IntelliJ-Rust-Playground/files/7255483/Rust.Playground-2.1.1.zip)
