### ISSUE TITLE
Exception in plugin Rust Playground (1.0.2)

### ISSUE THREAD

**Issue by teras** [cherryleafroad/IntelliJ-Rust-Playground#4]
Hello

I tried to install Rust Playground on my lastest IntelliJ distribution, and I got this error, which prohibits Playground to start.
Any ideas?

Thank you!

```
java.lang.NullPointerException
	at com.cherryleafroad.rust.playground.Helpers$cargoPlayInstallNotification$install$1.run(Helpers.kt:41)
	at com.intellij.notification.NotificationAction.lambda$createSimple$3(NotificationAction.java:55)
	at com.intellij.notification.NotificationAction$Simple.actionPerformed(NotificationAction.java:81)
	at com.intellij.notification.NotificationAction.actionPerformed(NotificationAction.java:30)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:267)
	at com.intellij.notification.Notification.fire(Notification.java:280)
	at com.intellij.notification.EventLog$2.hyperlinkUpdate(EventLog.java:192)
	at com.intellij.notification.EventLog$NotificationHyperlinkInfo.navigate(EventLog.java:653)
	at com.intellij.execution.impl.EditorHyperlinkSupport.lambda$getLinkNavigationRunnable$0(EditorHyperlinkSupport.java:158)
	at com.intellij.execution.impl.EditorHyperlinkSupport$1.mouseReleased(EditorHyperlinkSupport.java:83)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:3903)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3794)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by MolotovCherry** [comment]
Taking a look at the [line at fault](https://github.com/cherryleafroad/IntelliJ-Rust-Playground/blob/403be6ec9956c0bda1e0d5c04c8d86ec4590cf9c/src/main/kotlin/com/cherryleafroad/rust/playground/Helpers.kt#L41), it would appear that your Rust toolchain is either missing or not setup - at least as far as the official Rust intellij plugin is concerned.

Could you check and see if the official plugin sees your Rust installation properly? That should fix it. As for that specific error, I can fix that one as well. I'll make a quick patch for you and send you the plugin zip on this issue fixing it later today

Now, just to verify, this occurred after you clicked the install link? If not, could you tell me when and where it occurred and how (reproducible steps)?

If that the above tips didn't help you out, please reply with more details about your OS, IntelliJ edition + version, and what the official Rust plugin is showing you regarding toolchain stuff. Please also include as detailed as you can, steps that would be required to reproduce it (as seen from your end; telling little details allows me to better determine exactly where it may have failed). If there are any other pertinent details, please also include those

(Just an FYI, if the problem is indeed that your toolchain isn't being seen or setup properly, then solving this exception in my plugin still won't allow you to use the plugin, as the plugin needs both the Rust plugin to be properly set up + cargo-play installed. What you would see from your end is that clicking the installation link in the bubble simply does nothing)

Let me know what you find and we'll take it from there!

**Comment by teras** [comment]
Thank you for the quick reply!
I am a newcomer to Rust and indeed I might not have everything set up correctly (although I am able to compile Rust apps from the command line). So I thought that using the IDE I know well, and especially the playground should help me with this procedure.

**Comment by MolotovCherry** [comment]
Another thought too, but did you create a Rust project, or is it not on a Rust project? I'm wondering if perhaps that was the cause of the toolchain "not being found". The plugin only works when you're in a Rust project and make a Rust scratch file (it doesn't matter if your real project is empty)

Anyways, let me know what you find and we'll take it from there ;)

**Comment by MolotovCherry** [comment]
> Thank you for the quick reply!
> I am a newcomer to Rust and indeed I might not have everything set up correctly (although I am able to compile Rust apps from the command line). So I thought that using the IDE I know well, and especially the playground should help me with this procedure.

Here's a quick hotfix for you. Please try it out and let me know if it works for you. You'll have to install it manually. Please note that even though it won't crash on you, if the toolchain is unavailable, the install link will simply do nothing (toolchain + Rust plugin detecting it is a separate issue not under my control). If it still crashes on you, please let me know asap so I can fix that too
[Rust Playground-1.0.3.zip](https://github.com/cherryleafroad/IntelliJ-Rust-Playground/files/6415301/Rust.Playground-1.0.3.zip)

(You can also go into the command line and `cargo install cargo-play`, but the toolchain not showing up is probably a larger problem -> You can find the settings at `Language & Frameworks -> Rust`)

**Comment by teras** [comment]
Indeed the problem is with my installation of Rust.
For some reason the main Rust plugin doesn't recognize it and it fails to properly create a Rust project under IntelliJ.

Thank you for your time, maybe I should fix this problem first!

I tried the new plugin and it doesn't crash. Which is a good thing.
Maybe you can close this issue for now?

**Comment by MolotovCherry** [comment]
Glad to hear it's not crashing now! Good luck with fixing your Rust installation/Rust plugin settings.
